vayu: Remove unneded defenition Causes Duplication errors:
error: found duplicate sysprop assignments:
pm.dexopt.install=speed
pm.dexopt.install=speed-profile
error: found duplicate sysprop assignments:
pm.dexopt.first-boot=speed
pm.dexopt.first-boot=verify